---
name: Super-Linter

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true  # This option will cancel all in-progress jobs if any matrix job fails.
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          FILTER_REGEX_EXCLUDE: .*\.md$
          
        continue-on-error: false  # This option will mark the workflow as failed if this step fails.
